### PR TITLE
Add cursorword_toggle_cursorline_bg option

### PR DESCRIPTION
**Pull request by weeman1337**
Setting this opion keeps the cursorline background while moving the cursor.

### CODE REVIEW

**Comment by Shatur95** [comment]
@weeman1337, I didn't see your PR and sent my own before that in which I simply removed this functionality because I thought that it was not needed :D
Probably it would be better to just disable `CursorMoved,CursorMovedI` events if this option is enable. @yamatsum, what do you think?

**Comment by yamatsum** [comment]
In addition to the default settings, why not make one that always highlights and one that doesn't always highlight (use only cursorwords)?

**Comment by yamatsum** [comment]
@weeman1337 @Shatur 
In addition to the default settings, why not make one that always highlights and one that doesn't always highlight (use only cursorwords)?

**Comment by weeman1337** [comment]
> In addition to the default settings, why not make one that always highlights and one that doesn't always highlight (use only cursorwords)?

Instead of adding a dedicated option to nvim-cursorline shouldn't it pick up the `set cursorline` value? After clarifying that I will update the PR.

**Comment by yamatsum** [comment]
Does that mean `o.cursorline = false` and use only cursorwords?

**Comment by weeman1337** [comment]
> Does that mean o.cursorline = false and use only cursorwords?

No it prevents that the background is removed while moving the cursor.

I am not sure that to do now. What I want to achieve is that the background highlight of the line won't be removed while moving the cursor around. I am fine with any option name.

**Comment by weeman1337** [comment]
Setting `cursorline_timeout` to 0 does the job

**Comment by yamatsum** [comment]
If you set it to always show it, you will have a performance problem. Therefore, I try not to deliberately see it while I'm on the move.

**Pull request closed without merging**
