### PR TITLE
added support for disabling cursorline updates if cursorline_timeout set to 0

### LINKED ISSUE #12: Option to disable cursorline timeout completely
Hello, it seems that the cursorline keeps flashing everytime it is updated (if vim.g.cursorline_timeout is set to 0). This seems to be due to the timer updating the cursorline to the same colour.

### PR DESCRIPTION
**Pull request by axieax**
fixes #12

### CODE REVIEW

**Comment by yamatsum** [comment]
> However, I just found out that my changes cause unexpected behaviour, such as cursorline in Telescope query fields. Could you see if you can fix this as well before merging?
UPDATE: this seems to be another issue (not caused by me)

Are you saying that ultimately there are no issues with this PR?

**Comment by axieax** [comment]
I don't really remember since it's been months, but I believe so :)

**Comment by yamatsum** [comment]
@axieax 
Thanks for the PR!
I've merged it, so if everything's okay, please close the issue!

**Comment by yamatsum** [comment]
@axieax
Thanks for the PR!
If you have more problems, please reopen the issue or create another issue

**Pull request merged**
