### PR TITLE
feat: configurable cursorline timeout

### PR DESCRIPTION
**Pull request by andersevenrud**
Since this plugin does not rely on the `updatetime` setting in vim then I assume it's safe to change this value without much of an performance impact.

I like to have this feature a bit more snappy, hence this PR.

The one thing I'm not sure about is the name of the variable used to configure this setting. I just stuck with the prefix that was already used in another one. I also saw that #6 did the same thing.

Maybe consider prefixing it with `cursorline_` instead to make it match the name of the plugin ?

### CODE REVIEW

**Comment by andersevenrud** [comment]
Oh. I just read #8 and it seems to remove this feature entirely ? :thinking:

**Comment by Shatur95** [comment]
> Oh. I just read #8 and it seems to remove this feature entirely ? thinking

This is a very strange functionality that cannot be configured, so I thought it was a bug: D But then I realized that this is such a feature.

**Comment by weeman1337** [comment]
Any news about that? Setting that to 0 would solve #6 as well.

**Comment by lyonelz96** [comment]
This is what I was looking for! I feel the time it takes for the highlight to appear is a bit too long. Wonder why this hasn't been merged yet. 🤔

**Comment by andersevenrud** [comment]
@lyonelz96 I haven't heard from @yamatsum yet, so I'm not sure :) You can easily use this branch in your plugin manager to make use of the functionality though.

**Comment by yamatsum** [comment]
@andersevenrud 
Thank you for PR. And I'm sorry for the late reply.
I just merged!

**Comment by andersevenrud** [comment]
No worries @yamatsum. Happy to contribute :)

**Comment by andersevenrud** [comment]
Also, thanks :blush:

**Comment by yamatsum** [comment]
After that, changed prefix!

**Pull request merged**
